"""Pose reliability status labels for Milestone 2."""

from __future__ import annotations

from enum import StrEnum


class FrameQualityStatus(StrEnum):
    """Frame-level target/pose quality state."""

    VALID_TARGET = "VALID_TARGET"
    LOW_POSE_CONFIDENCE = "LOW_POSE_CONFIDENCE"
    PARTIAL_POSE = "PARTIAL_POSE"
    TARGET_IDENTITY_UNCERTAIN = "TARGET_IDENTITY_UNCERTAIN"
    TARGET_NOT_FOUND = "TARGET_NOT_FOUND"
    ATHLETE_TOO_SMALL = "ATHLETE_TOO_SMALL"
    SEVERE_OCCLUSION = "SEVERE_OCCLUSION"
    INVALID_TRACK_SEGMENT = "INVALID_TRACK_SEGMENT"


class LandmarkQualityStatus(StrEnum):
    """Landmark-level quality state."""

    OBSERVED_VALID = "OBSERVED_VALID"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    TEMPORAL_OUTLIER = "TEMPORAL_OUTLIER"
    IDENTITY_UNCERTAIN = "IDENTITY_UNCERTAIN"
    MISSING = "MISSING"
    REJECTED = "REJECTED"


class ProcessingStatus(StrEnum):
    """Coordinate processing provenance labels."""

    RAW_VALID = "RAW_VALID"
    INTERPOLATED = "INTERPOLATED"
    SMOOTHED = "SMOOTHED"
    REJECTED_LOW_CONFIDENCE = "REJECTED_LOW_CONFIDENCE"
    REJECTED_TEMPORAL_OUTLIER = "REJECTED_TEMPORAL_OUTLIER"
    REJECTED_IDENTITY_UNCERTAIN = "REJECTED_IDENTITY_UNCERTAIN"
    REJECTED_INVALID_TRACK_SEGMENT = "REJECTED_INVALID_TRACK_SEGMENT"
    MISSING = "MISSING"
